import 'bootstrap/dist/css/bootstrap.css'
import './global.css'
import type { AppProps } from 'next/app'
import gsap from 'gsap'
import ScrollTrigger from 'gsap/ScrollTrigger'
import Layout from '@/components/Layout'
import Head from 'next/head'
import SotmAward from '@/components/Molecules/SotmAward'

gsap.registerPlugin(ScrollTrigger)

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>HERR Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
      <SotmAward />
    </>
  )
}
