import 'bootstrap/dist/css/bootstrap.css'
import './global.css'
import type { AppProps } from 'next/app'
import gsap from 'gsap'
import ScrollTrigger from 'gsap/ScrollTrigger'
import Layout from '@/components/Layout'
import Head from 'next/head'
import SotmAward from '@/components/Molecules/SotmAward'
import { Analytics } from '@vercel/analytics/react'

gsap.registerPlugin(ScrollTrigger)

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>HERR Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="keywords" content="software engineer, developer, frontend, portfolio, resume, graphic designer, photographer, video editor, HERR, Teng Wei Herr" />
        <meta name="author" content="Teng Wei Herr" />
        <meta name="image" content="https://www.herr.my/asset/herr-orange.jpg" /> 
        <meta name="robots" content="index, follow" />
        <meta name="googlebot" content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1" />
        <meta name="bingbot" content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1" />
        <meta property="og:title" content="Teng Wei Herr | HERR Studio" />
        <meta property="og:description" content="Software Engineer, Freelance Motion Graphic Designer and Photographer in Malaysia. Open to freelance or any new opportunities." />
        <meta property="og:image" content="https://www.herr.my/asset/herr-orange.jpg" />
        <meta property="og:url" content="https://www.herr.my/" />
        <meta property="og:type" content="website" />
        <meta property="og:locale" content="en_US" />
        <meta property="og:site_name" content="Teng Wei Herr | HERR Studio" />
        <meta property="og:image:width" content="512" />
        <meta property="og:image:height" content="512" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Teng Wei Herr | HERR Studio" />
        <meta name="twitter:description" content="Software Engineer, Freelance Motion Graphic Designer and Photographer in Malaysia. Open to freelance or any new opportunities." />
        <meta name="twitter:image" content="https://www.herr.my" />
      </Head>
        {/* Global site tag (gtag.js) - Google Analytics */}
        {/* <Script async src="https://www.googletagmanager.com/gtag/js?id=UA-210223692-1" />
        <Script async id='gtag'>
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'UA-210223692-1');
          `}
        </Script> */}
      <Layout>
        <Component {...pageProps} />
        <Analytics />
      </Layout>
      <SotmAward />
    </>
  )
}
