import 'bootstrap/dist/css/bootstrap.css'
import 'react-loading-skeleton/dist/skeleton.css'
import './global.css'
import type { AppProps } from 'next/app'
import gsap from 'gsap'
import ScrollTrigger from 'gsap/ScrollTrigger'
import Layout from '@/components/Layout'
import Head from 'next/head'
import SotyAward from '@/components/Molecules/SotyAward'
import { Profiler } from 'react'
import { createGlobalStyle } from 'styled-components'

gsap.registerPlugin(ScrollTrigger)

const GlobalStyle = createGlobalStyle`
  @font-face {
    font-family: 'Geist';
    src: url('/fonts/Geist/Geist-Thin.otf') format('otf');
    font-style: normal;
    font-weight: 100;
    font-display: swap;
  }
  @font-face {
    font-family: 'Geist';
    src: url('/fonts/Geist/Geist-UltraLight.otf') format('otf');
    font-style: normal;
    font-weight: 200;
    font-display: swap;
  }
  @font-face {
    font-family: 'Geist';
    src: url('/fonts/Geist/Geist-Light.otf') format('otf');
    font-style: normal;
    font-weight: 300;
    font-display: swap;
  }
  @font-face {
    font-family: 'Geist';
    src: url('/fonts/Geist/Geist-Regular.otf') format('otf');
    font-style: normal;
    font-weight: 400;
    font-display: swap;
  }
  @font-face {
    font-family: 'Geist';
    src: url('/fonts/Geist/Geist-Medium.otf') format('otf');
    font-style: normal;
    font-weight: 500;
    font-display: swap;
  }
  @font-face {
    font-family: 'Geist';
    src: url('/fonts/Geist/Geist-SemiBold.otf') format('otf');
    font-style: normal;
    font-weight: 600;
    font-display: swap;
  }
  @font-face {
    font-family: 'Geist';
    src: url('/fonts/Geist/Geist-Bold.otf') format('otf');
    font-style: normal;
    font-weight: 700;
    font-display: swap;
  }
  @font-face {
    font-family: 'Geist';
    src: url('/fonts/Geist/Geist-Black.otf') format('otf');
    font-style: normal;
    font-weight: 800;
    font-display: swap;
  }
  @font-face {
    font-family: 'Geist';
    src: url('/fonts/Geist/Geist-UltraBlack.otf') format('otf');
    font-style: normal;
    font-weight: 900;
    font-display: swap;
  }
`

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <GlobalStyle />
      <Profiler id="app" onRender={() => {}}>
        <Head>
          <title>
            Teng Wei Herr - Software Engineer, Tech Writer, Designer and
            Photographer
          </title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <meta
            name="keywords"
            content="software engineer, developer, frontend, portfolio, resume, graphic designer, photographer, video editor, HERR, Teng Wei Herr"
          />
          <meta name="author" content="Teng Wei Herr" />
          <meta
            name="image"
            content="https://www.herr.my/asset/herr-orange.jpg"
          />
          <meta name="robots" content="index, follow" />
          <meta
            name="googlebot"
            content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1"
          />
          <meta
            name="bingbot"
            content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1"
          />
          <meta property="og:title" content="Teng Wei Herr | HERR Studio" />
          <meta
            property="og:description"
            content="Software Engineer, Freelance Motion Graphic Designer and Photographer in Malaysia. Open to freelance or any new opportunities."
          />
          <meta
            property="og:image"
            content="https://www.herr.my/asset/herr-orange.jpg"
          />
          <meta property="og:url" content="https://www.herr.my/" />
          <meta property="og:type" content="website" />
          <meta property="og:locale" content="en_US" />
          <meta property="og:site_name" content="Teng Wei Herr | HERR Studio" />
          <meta property="og:image:width" content="512" />
          <meta property="og:image:height" content="512" />
          <meta name="twitter:card" content="summary_large_image" />
          <meta name="twitter:title" content="Teng Wei Herr | HERR Studio" />
          <meta
            name="twitter:description"
            content="Software Engineer, Freelance Motion Graphic Designer and Photographer in Malaysia. Open to freelance or any new opportunities."
          />
          <meta name="twitter:image" content="https://www.herr.my" />
        </Head>
        <Layout>
          <Component {...pageProps} />
        </Layout>
        <SotyAward />
      </Profiler>
    </>
  )
}
