import Head from 'next/head'
import { Inter } from 'next/font/google'
import gsap from 'gsap'
import { CONTENTFUL_ACCESS_TOKEN, CONTENTFUL_SPACE_ID } from '@/utils/const'
import Header from '@/components/Layout/Header'
import SotmAward from '@/components/SotmAward'
import Footer from '@/components/Layout/Footer'
import Body from '@/components/Layout/Body'
import Banner from '@/components/Banner'
import ScrollTrigger from 'gsap/ScrollTrigger'

const inter = Inter({ subsets: ['latin'] })

const query = `{
  experienceCollection {
    items {
        role
        company
        startTime
        endTime
        description {
          json
        }
    }
  }
}`

// Here are our options to use with fetch
const fetchOptions = {
  spaceID: CONTENTFUL_SPACE_ID,
  accessToken: CONTENTFUL_ACCESS_TOKEN,
  method: "POST",
  headers: {
    Authorization: `Bearer ${CONTENTFUL_ACCESS_TOKEN}`,
    "Content-Type": "application/json",
  },
  body: JSON.stringify({ query })
}

// This function gets called at build time
export async function getStaticProps() {
  // Call an external API endpoint to get posts

  const res = await fetch("https://graphql.contentful.com/content/v1/spaces/9tnwp5z6xqrq", fetchOptions)
  const data = await res.json()

  // console.log(data.data.experienceCollection.items)

  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      data,
    },
  }
}

gsap.registerPlugin(ScrollTrigger); 

export default function Home() {

  return (
    <>
      <Head>
        <title>HERR Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />  
      </Head>
      <Header />
      <Body>
        <Banner />
      </Body>
      <Footer />
      <SotmAward />
    </>
  )
}
