import Head from 'next/head'
import { fetchExp, fetchMyData, fetchProjects } from '@/utils/api/contentful'
import Header from '@/components/Layout/Header'
import SotmAward from '@/components/Molecules/SotmAward'
import Footer from '@/components/Layout/Footer'
import Body from '@/components/Layout/Body'
import Banner from '@/components/Sections/Banner'
import Quote1 from '@/components/Sections/Quote1'
import Highlight from '@/components/Sections/Highlight'
import Introduction from '@/components/Sections/Introduction'
import { Experience as Exp, MyData, Project } from '@/utils/types'
import Experience from '@/components/Sections/Experience'
import More from '@/components/Sections/More'
import Contact from '@/components/Sections/Contact'

type HomeProps = {
  projects: Array<Project>
  myData: MyData
  exps: Array<Exp>
}

// This function gets called at build time
export async function getStaticProps() {

  const projects = await fetchProjects()
  const myData = await fetchMyData()
  const exps = await fetchExp()

  return {
    props: {
      projects,
      myData,
      exps
    },
  }
}

export default function Home({projects,myData,exps}:HomeProps) {

  return (
    <>
      <Head>
        <title>HERR Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />  
      </Head>
      <Header resume={myData.resume}/>
      <Body>
        <Banner />
        <Quote1 />
        <Highlight projects={projects}/>
        <Introduction myData={myData}/>
        <Experience exps={exps}/>
        <More />
        <Contact />
      </Body>
      <Footer />
      <SotmAward />
    </>
  )
}
