import Head from 'next/head'
import Header from '@/components/Layout/Header'
import SotmAward from '@/components/SotmAward'
import Footer from '@/components/Layout/Footer'
import Body from '@/components/Layout/Body'
import Banner from '@/components/Banner'
import Quote1 from '@/components/Quote1'
import Highlight from '@/components/Highlight'
import { fetchProjects } from '@/utils/api/contentful'

type Project = {
  title: string
  role: string
  tools: string
  description: string
  githubLink: string
  projectLink?: string
  awardWinning: boolean
  highlighted: boolean
  image: {
    url: string
    width: number
    height: number
  }
}

type HomeProps = {
  projects: Array<Project>
}

// This function gets called at build time
export async function getStaticProps() {

  const projects = await fetchProjects()

  return {
    props: {
      projects,
    },
  }
}

export default function Home({projects}:HomeProps) {

  return (
    <>
      <Head>
        <title>HERR Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />  
      </Head>
      <Header />
      <Body>
        <Banner />
        <Quote1 />
        <Highlight projects={projects}/>
      </Body>
      <Footer />
      <SotmAward />
    </>
  )
}
