const CONTENTFUL_SPACE_ID = process.env.CONTENTFUL_SPACE_ID
const CONTENTFUL_ACCESS_TOKEN = process.env.CONTENTFUL_ACCESS_TOKEN
const CONTENTFUL_PREVIEW_ACCESS_TOKEN = process.env.CONTENTFUL_PREVIEW_ACCESS_TOKEN
const CONTENTFUL_PREVIEW_SECRET = process.env.CONTENTFUL_PREVIEW_ACCESS_TOKEN

const EMAIL_LINK = 'weiherrteng@gmail.com'
const BEHANCE_LINK = 'https://www.behance.net/herrstudio'
const RESUME_LINK = 'https://docs.google.com/document/d/1om2VxDwWsIYzytPMjW8fYrsmzeYiX73Z7-n_LGPGcPc/edit?usp=share_link'

export { 
    CONTENTFUL_SPACE_ID,
    CONTENTFUL_ACCESS_TOKEN,
    CONTENTFUL_PREVIEW_ACCESS_TOKEN,
    CONTENTFUL_PREVIEW_SECRET,
    EMAIL_LINK,
    BEHANCE_LINK,
    RESUME_LINK
}